### ISSUE TITLE
Can you show a demonstration (screencast?)

### ISSUE THREAD

**Issue by luzpaz** [VyacheslavKlipov/PlacementTools#1]
I would love to understand what this project does exactly

**Comment by luzpaz** [comment]
bump @VyacheslavKlipov

**Comment by VyacheslavKlipov** [comment]
https://www.youtube.com/watch?v=UEwlEG8g-JM&list=PLfTREYIFdFHe1eTUVBKYjvOOIleLJiH10&index=2

https://www.youtube.com/watch?v=aeRd-NzHrhI&list=PLfTREYIFdFHe1eTUVBKYjvOOIleLJiH10&index=1

**Comment by luzpaz** [comment]
Cool! Is this something that you can port to work in v0.20dev ? 

Also have you seen https://github.com/easyw/Manipulator workbench? Maybe worth collaborating ? CC @easyw

**Comment by VyacheslavKlipov** [comment]
Yes, I have seen the Manipulator. You have a different approach. But I can collaborate with you.
