### ISSUE TITLE
README: Make multi-lingual (include english)

### ISSUE THREAD

**Issue by luzpaz** [VyacheslavKlipov/PlacementTools#3]

**Comment by VyacheslavKlipov** [comment]
Maybe someday. This is so intuitively understandable.

**Comment by luzpaz** [comment]
The reason: possible inclusion in to the FreeCAD [Addon Manager](https://github.com/FreeCAD/FreeCAD-addons/)

**Comment by VyacheslavKlipov** [comment]
Yes, I know, but now we need to focus on functionality. Have you seen the new G and L button? This enables and disables group object accounting. This is very handy for design. This is not yet implemented for all instruments.

**Comment by luzpaz** [comment]
Can you share your progress on the forum? The community would like this, I think.

**Comment by VyacheslavKlipov** [comment]
Yes, I created a topic in Development->Assembly on the forum. I have not used the forum before. I hope I did everything right.

**Comment by luzpaz** [comment]
URL?

**Comment by VyacheslavKlipov** [comment]
https://forum.freecadweb.org/viewtopic.php?f=20&t=66526

**Comment by luzpaz** [comment]
To make this workbench multi-lingual, we recommend reading https://github.com/FreeCAD/Addons/issues/15

**Comment by VyacheslavKlipov** [comment]
Well, I finally won. I made it multilingual!

**Comment by luzpaz** [comment]
commit?

**Comment by VyacheslavKlipov** [comment]
yes

**Comment by luzpaz** [comment]
08d5e8e0a488632e07a7fcf304e75bbba22f0aae
