### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by luzpaz** [VyacheslavKlipov/PlacementTools#7]

**Comment by VyacheslavKlipov** [comment]
I added a link to the GPL license in
README.md file.

**Comment by luzpaz** [comment]
JFTR, it's customary to add a LICENSE file to the repo. It may also raise the probability of the license being respected

**Comment by VyacheslavKlipov** [comment]
I added.

**Comment by luzpaz** [comment]
Note: it doesn't need an extension `.txt` It simply can be named `LICENSE`
